src/Entity/Championnats.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChampionnatsRepository")
 */
class Championnats
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbr_jours;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="championnats")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Matchs", mappedBy="championnat")
     */
    private $matchs;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Classement", mappedBy="championnat", cascade={"persist", "remove"})
     */
    private $classement;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $close;
    

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->matchs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbrJours(): ?int
    {
        return $this->nbr_jours;
    }

    public function setNbrJours(int $nbr_jours): self
    {
        $this->nbr_jours = $nbr_jours;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
        }

        return $this;
    }


    
    /**
     * @return Collection|Matchs[]
     */
    public function getMatchs(): Collection
    {
        return $this->matchs;
    }

    public function addMatch(Matchs $match): self
    {
        if (!$this->matchs->contains($match)) {
            $this->matchs[] = $match;
            $match->setChampionnat($this);
        }

        return $this;
    }

    public function removeMatch(Matchs $match): self
    {
        if ($this->matchs->contains($match)) {
            $this->matchs->removeElement($match);
            // set the owning side to null (unless already changed)
            if ($match->getChampionnat() === $this) {
                $match->setChampionnat(null);
            }
        }

        return $this;
    }

    public function getClassement(): ?Classement
    {
        return $this->classement;
    }

    public function setClassement(Classement $classement): self
    {
        $this->classement = $classement;

        // set the owning side of the relation if necessary
        if ($this !== $classement->getChampionnat()) {
            $classement->setChampionnat($this);
        }

        return $this;
    }

    public function getClose(): ?int
    {
        return $this->close;
    }

    public function setClose(?int $close): self
    {
        $this->close = $close;

        return $this;
    }

  
}

src/Entity/Matchs.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MatchsRepository")
 */
class Matchs
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="matchs")
     */
    private $Joueurs1;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $resultat_j1;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="matchs")
     */
    private $Joueurs2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $resultat_j2;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Championnats", inversedBy="matchs")
     */
    private $championnat;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $journee;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getJoueurs1(): ?User
    {
        return $this->Joueurs1;
    }

    public function setJoueurs1(?User $Joueurs1): self
    {
        $this->Joueurs1 = $Joueurs1;

        return $this;
    }

    public function getResultatJ1(): ?int
    {
        return $this->resultat_j1;
    }

    public function setResultatJ1(?int $resultat_j1): self
    {
        $this->resultat_j1 = $resultat_j1;

        return $this;
    }

    public function getJoueurs2(): ?User
    {
        return $this->Joueurs2;
    }

    public function setJoueurs2(?User $Joueurs2): self
    {
        $this->Joueurs2 = $Joueurs2;

        return $this;
    }

    public function getResultatJ2(): ?int
    {
        return $this->resultat_j2;
    }

    public function setResultatJ2(?int $resultat_j2): self
    {
        $this->resultat_j2 = $resultat_j2;

        return $this;
    }

    public function getChampionnat(): ?Championnats
    {
        return $this->championnat;
    }

    public function setChampionnat(?Championnats $championnat): self
    {
        $this->championnat = $championnat;

        return $this;
    }

    public function getJournee(): ?int
    {
        return $this->journee;
    }

    public function setJournee(?int $journee): self
    {
        $this->journee = $journee;

        return $this;
    }
}

src/Form/ChampionnatType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Championnats;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChampionnatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nbr_jours')
            ->add('users', EntityType::class, [
                'class' => User::class, 
                'choice_label'=>'username',
                'multiple'=>true            
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Championnats::class,
        ]);
    }
}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use App\Repository\MatchsRepository;
use App\Repository\ClassementRepository;
use App\Repository\ChampionnatsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class TournamentController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(UserRepository $repo, UserInterface $user = null, ClassementRepository $classementRepo)
    {
        if($user){
            $users = $repo->findBy(array('id' => $user->getId()))[0];
            $championnats = $users->getChampionnats();
            foreach($championnats as $championnat)
            {
                $classements[] = $classementRepo->findByOrder($championnat);
            }
        }
        else{
            $championnats = array();
            $classements = array();
        }

        return $this->render('tournament/index.html.twig', [
            'courant_menu' => 'home',
            'championnats' => $championnats,
            'classements'  => $classements
        ]);
    }

}

templates/tournament/championnat/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">

    <center>
        <h2>CHAMPIONNAT ID : {{championnat.id}} <small>Journée
                {% if journee.0.journee is defined %}{{journee.0.journee}}{% else %}0{% endif %}/{{championnat.nbrjours}}</small>
        </h2>
    </center>
    {% for message in app.flashes('error') %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-dismissible alert-danger">
                <i class="fas fa-exclamation-triangle"></i> {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if championnat.close != 1 %}
    <a class="btn btn-success btn btn-block col-md-2 offset-md-10" role="button" aria-disabled="true" tabindex="-1"
        href="{{ path('closeChampionnat', {'id' : championnat.id} )}}">
        Terminer championnat
    </a>
    {% else %}
    <h4 class="text-info" style="text-align: center;">Championnat Fini</h4>
    {% endif %}


    <hr>

    <div class="row">
        <div class="col-md-12">
            <h5>Joueurs :</h5>
        </div>
        {% for user in users %}

        <div class="col-md-2">
            <div class="card" style="height: 12rem;">
                <img src="{{vich_uploader_asset(user, 'imageFile') | imagine_filter('medium')}}" alt=""
                    class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title" style="text-align: center;">{{user.username}}</h5>
                    <p class="card-text" style="text-align: center;">
                        {% if user.victory != null %}
                        {% set val = user.victory - 1 %}
                        {% for i in 0..val  %}
                        <i style="color:gold" class="fas fa-star"></i>
                        {% endfor %}
                        {% endif %}
                        <!-- <i class="fas fa-star-of-david"></i> -->
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <h5>Match joués :</h5>
            {% if championnat.close != 1 %}
            <a class="btn btn-warning btn-lg btn-block col-md-12" role="button" aria-disabled="true" tabindex="-1"
                href="{{ path('editMatch', {'id' : championnat.id} )}}">Ajouter un match</a>
            {% endif %}
            <table class="table table-hover table-striped table-bordered table-sm col-md-12" style="text-align:center">
                <thead>
                    <tr>
                        <th>
                            Journée
                        </th>
                        <th>
                            J1
                        </th>
                        <th>
                            Résultat J1
                        </th>
                        <th>
                            Résultat J2
                        </th>
                        <th>
                            J2
                        </th>
                        <th>
                            Edit
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for match in matchs %}
                    <tr>
                        <td>
                            {{match.journee}}
                        </td>
                        <td>
                            {{match.joueurs1.username}}
                        </td>
                        <td>
                            {% if match.resultatj1 > match.resultatj2 %}
                            {% set color ="green" %}
                            {% else %}
                            {% set color ="red" %}
                            {% endif %}
                            <span style="color:{{ color}}">{{match.resultatj1}}</span>
                        </td>
                        <td>
                            {% if match.resultatj1 < match.resultatj2 %}
                            {% set color ="green" %}
                            {% else %}
                            {% set color ="red" %}
                            {% endif %}
                            <span style="color:{{ color}}">{{match.resultatj2}}</span>
                        </td>
                        <td>
                            {{match.joueurs2.username}}
                        </td>
                        <td>
                            <a href="{{path('deleteMatch', {'id' : match.id} )}}" class="href"><i
                                    class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <h5>Classement :</h5>
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th scope="col">J</th>
                            <th scope="col">MJ</th>
                            <th scope="col">G</th>
                            <th scope="col">N</th>
                            <th scope="col">D</th>
                            <th scope="col">BP</th>
                            <th scope="col">BC</th>
                            <th scope="col">DB</th>
                            <th scope="col">Pts</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for data in classement %}
                        <tr>
                            <th>{{ data.user.username }}</th>
                            <th>{{ data.mj }}</th>
                            <td>{{ data.g }}</td>
                            <td>{{ data.n }}</td>
                            <td>{{ data.d }}</td>
                            <td>{{ data.bp }}</td>
                            <td>{{ data.bc }}</td>
                            <td>{{ data.db }}</td>
                            <td>{{ data.pts }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css">
{% endblock %}


{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('select').select2();

    });

</script>
{% endblock %}